export const INTEGRATION_TYPE = {
	NONE: 0x0,
	OBS: 0x1,
	ETC: 0x2,
	MEDIA: 0x3
};

export const INTEGRATION_LABELS = {
	[INTEGRATION_TYPE.NONE]: 'NONE',
	[INTEGRATION_TYPE.OBS]: 'OBS',
	[INTEGRATION_TYPE.ETC]: 'ETC',
	[INTEGRATION_TYPE.MEDIA]: 'MEDIA'
};